Update .readthedocs.yml to use py3.8
Update .readthedocs.yml

Update .readthedocs.yml

Update .readthedocs.yml

Update .readthedocs.yml

Update .readthedocs.yml

add pillow <=9.5.0

PIL fails on RTD due to AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS' . Based on https://github.com/JaidedAI/EasyOCR/issues/1077 let us try to add pillow with <=9.5.0 . Pillow is not part of RTD from aug 2023 os good to add it here anyway

Update requirements.txt

Update .readthedocs.yml

Update requirements.txt